[project]
name = 'contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.ahmed]
path = 'contracts/ahmed.clar'
clarity_version = 2
epoch = 2.4

[contracts.stack]
path = 'contracts/stack.clar'
clarity_version = 2
epoch = 2.4

[contracts.stack1]
path = 'contracts/stack1.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
